import { Octokit } from "octokit";

/**
 * Creates an authenticated Octokit instance for pushing code to GitHub.
 */
export function createOctokit(accessToken: string) {
  return new Octokit({ auth: accessToken });
}

/**
 * Resolves the default branch name for a repo (could be "main" or "master").
 */
async function getDefaultBranch(
  octokit: Octokit,
  owner: string,
  repo: string
): Promise<string> {
  const { data } = await octokit.rest.repos.get({ owner, repo });
  return data.default_branch;
}

/**
 * Creates a repository (or reuses existing) and pushes a set of files in a
 * single commit using the Git tree/blobs API.
 */
export async function pushToGitHub(
  accessToken: string,
  owner: string,
  repoName: string,
  files: { path: string; content: string }[],
  commitMessage: string = "🚀 Deploy portfolio via GitFolio Engine"
) {
  const octokit = createOctokit(accessToken);

  // 1. Create the repository — or get the existing one on 422 (already exists)
  try {
    await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName,
      description: "My developer portfolio — generated by GitFolio Engine",
      auto_init: true,
      has_pages: false,
    });

    // Give GitHub a moment to finish initialising the repo
    await new Promise((r) => setTimeout(r, 1500));
  } catch (error: unknown) {
    const err = error as { status?: number };
    if (err.status !== 422) {
      // 422 = repo already exists, anything else is a real error
      throw error;
    }
  }

  // 2. Resolve the real default branch (could be "main" or "master")
  const defaultBranch = await getDefaultBranch(octokit, owner, repoName);

  // 3. Get the current HEAD commit SHA
  const { data: ref } = await octokit.rest.git.getRef({
    owner,
    repo: repoName,
    ref: `heads/${defaultBranch}`,
  });
  const latestCommitSha = ref.object.sha;

  // 4. Create blobs for each file
  const blobs = await Promise.all(
    files.map(async (file) => {
      const { data: blob } = await octokit.rest.git.createBlob({
        owner,
        repo: repoName,
        content: Buffer.from(file.content).toString("base64"),
        encoding: "base64",
      });
      return { path: file.path, sha: blob.sha };
    })
  );

  // 5. Create a tree from blobs
  const { data: tree } = await octokit.rest.git.createTree({
    owner,
    repo: repoName,
    base_tree: latestCommitSha,
    tree: blobs.map((blob) => ({
      path: blob.path,
      mode: "100644" as const,
      type: "blob" as const,
      sha: blob.sha,
    })),
  });

  // 6. Create a commit
  const { data: commit } = await octokit.rest.git.createCommit({
    owner,
    repo: repoName,
    message: commitMessage,
    tree: tree.sha,
    parents: [latestCommitSha],
  });

  // 7. Move the branch reference to the new commit
  await octokit.rest.git.updateRef({
    owner,
    repo: repoName,
    ref: `heads/${defaultBranch}`,
    sha: commit.sha,
  });

  return {
    repoUrl: `https://github.com/${owner}/${repoName}`,
    commitSha: commit.sha,
    pagesUrl: `https://${owner}.github.io/${repoName}`,
    branch: defaultBranch,
  };
}
